import type { Product } from "@/types";

// Données de démonstration — remplacées par Drizzle + DB plus tard

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "cable-starlink-45m-renforce",
    name: "Câble Starlink 45 m renforcé anti-UV",
    reference: "CAB-45M-01",
    price: 38000,
    promoPrice: undefined,
    stock: 12,
    status: "in_stock",
    categoryId: "cables-connectique",
    images: ["/images/cable.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p2",
    slug: "support-toiture-inclinable",
    name: "Support de toiture inclinable",
    reference: "SUP-TOI-02",
    price: 25500,
    stock: 8,
    status: "in_stock",
    categoryId: "supports-fixations",
    images: ["/images/antenne-starlink.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p3",
    slug: "onduleur-1000va-starlink",
    name: "Onduleur 1000 VA pour Starlink",
    reference: "OND-1000",
    price: 84000,
    promoPrice: 67500,
    stock: 5,
    status: "in_stock",
    categoryId: "energie-onduleurs",
    images: ["/images/onduleur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p4",
    slug: "routeur-wifi-maille",
    name: "Routeur Wi-Fi maillé compatible",
    reference: "RTR-MESH",
    price: 65000,
    stock: 0,
    status: "on_order",
    categoryId: "antennes-routeurs",
    images: ["/images/routeur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p5",
    slug: "passe-mur-etanche",
    name: "Passe-mur étanche pour câble",
    reference: "PM-ETA-01",
    price: 7500,
    stock: 40,
    status: "in_stock",
    categoryId: "protection-etancheite",
    images: ["/images/passe-mur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p6",
    slug: "connecteur-rj45-blinde",
    name: "Connecteur de rechange RJ45 blindé",
    reference: "CON-RJ45",
    price: 4000,
    stock: 60,
    status: "in_stock",
    categoryId: "cables-connectique",
    images: ["/images/connecteur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p7",
    slug: "kit-starlink-standard",
    name: "Kit Starlink Standard complet",
    reference: "KIT-STD-01",
    price: 450000,
    stock: 3,
    status: "in_stock",
    categoryId: "kits-starlink",
    images: ["/images/kit-starlink.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p8",
    slug: "fixations-20-pieces",
    name: "Kit de fixations (20 pièces)",
    reference: "FIX-20",
    price: 3500,
    stock: 100,
    status: "in_stock",
    categoryId: "supports-fixations",
    images: ["/images/fixations.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
];

export const FLASH_SALE_END = Date.now() + 2 * 24 * 3600 * 1000; // +2 jours

export const FLASH_PRODUCTS = DEMO_PRODUCTS.filter((p) =>
  ["p1", "p3", "p5", "p6"].includes(p.id)
).map((p) => ({
  ...p,
  promoPrice:
    p.promoPrice ?? Math.round((p.price * 0.8) / 500) * 500,
}));
