import type { Product } from "@/types";

// Données de démonstration — remplacées par Drizzle + DB plus tard

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "cable-starlink-45m-renforce",
    name: "Câble Starlink 45 m renforcé anti-UV",
    reference: "CAB-45M-01",
    price: 38000,
    promoPrice: undefined,
    stock: 12,
    status: "in_stock",
    categoryId: "cables-connectique",
    images: ["/images/cable.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p2",
    slug: "support-toiture-inclinable",
    name: "Support de toiture inclinable",
    reference: "SUP-TOI-02",
    price: 25500,
    stock: 8,
    status: "in_stock",
    categoryId: "supports-fixations",
    images: ["/images/antenne-starlink.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p3",
    slug: "onduleur-1000va-starlink",
    name: "Onduleur 1000 VA pour Starlink",
    reference: "OND-1000",
    price: 84000,
    promoPrice: 67500,
    stock: 5,
    status: "in_stock",
    categoryId: "energie-onduleurs",
    images: ["/images/onduleur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p4",
    slug: "routeur-wifi-maille",
    name: "Routeur Wi-Fi maillé compatible",
    reference: "RTR-MESH",
    price: 65000,
    stock: 0,
    status: "on_order",
    categoryId: "antennes-routeurs",
    images: ["/images/routeur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p5",
    slug: "passe-mur-etanche",
    name: "Passe-mur étanche pour câble",
    reference: "PM-ETA-01",
    price: 7500,
    stock: 40,
    status: "in_stock",
    categoryId: "protection-etancheite",
    images: ["/images/passe-mur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p6",
    slug: "connecteur-rj45-blinde",
    name: "Connecteur de rechange RJ45 blindé",
    reference: "CON-RJ45",
    price: 4000,
    stock: 60,
    status: "in_stock",
    categoryId: "cables-connectique",
    images: ["/images/connecteur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p7",
    slug: "kit-starlink-standard",
    name: "Kit Starlink Standard complet",
    reference: "KIT-STD-01",
    price: 450000,
    stock: 3,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/kit-starlink.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p8",
    slug: "fixations-20-pieces",
    name: "Kit de fixations (20 pièces)",
    reference: "FIX-20",
    price: 3500,
    stock: 100,
    status: "in_stock",
    categoryId: "supports-fixations",
    images: ["/images/fixations.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p9",
    slug: "adaptateur-ethernet-starlink-gen3",
    name: "Adaptateur Ethernet Starlink Gen 3",
    reference: "STL-ETH-G3",
    price: 42000,
    stock: 15,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/connecteur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p10",
    slug: "support-mural-starlink",
    name: "Support mural Starlink renforcé",
    reference: "STL-MUR-01",
    price: 28000,
    stock: 10,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/antenne-starlink.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p11",
    slug: "alimentation-starlink-gen2",
    name: "Alimentation de rechange Starlink Gen 2",
    reference: "STL-ALIM-G2",
    price: 95000,
    stock: 4,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/onduleur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p12",
    slug: "ssd-500go-nvme",
    name: "SSD NVMe 500 Go",
    reference: "SSD-500",
    price: 45000,
    stock: 20,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/routeur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p13",
    slug: "barrette-ram-8go-ddr4",
    name: "Barrette RAM DDR4 8 Go",
    reference: "RAM-8G-D4",
    price: 22000,
    promoPrice: 18500,
    stock: 30,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/kit-starlink.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "p14",
    slug: "souris-clavier-sans-fil",
    name: "Combo souris + clavier sans fil",
    reference: "CLV-SRS",
    price: 15000,
    stock: 25,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/connecteur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
];

export const FLASH_SALE_END = Date.now() + 2 * 24 * 3600 * 1000; // +2 jours

export const FLASH_PRODUCTS = DEMO_PRODUCTS.filter((p) =>
  ["p1", "p3", "p5", "p6"].includes(p.id)
).map((p) => ({
  ...p,
  promoPrice:
    p.promoPrice ?? Math.round((p.price * 0.8) / 500) * 500,
}));
