import type { Product } from "@/types";

// Catalogue initial — prix à 0 = "Prix sur demande", définis par l'admin à la publication

export const DEMO_PRODUCTS: Product[] = [
  // ── Ordinateurs neufs & occasion ──
  {
    id: "ord-01",
    slug: "unite-centrale-neuve",
    name: "Unité centrale neuve",
    reference: "UC-NEU-01",
    price: 0,
    stock: 5,
    status: "in_stock",
    categoryId: "ordinateurs",
    images: ["/images/ordinateur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ord-02",
    slug: "unite-centrale-occasion",
    name: "Unité centrale d'occasion (contrôlée)",
    reference: "UC-OCC-01",
    price: 0,
    stock: 4,
    status: "in_stock",
    categoryId: "ordinateurs",
    images: ["/images/ordinateur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "ord-03",
    slug: "desktop-occasion-complet",
    name: "Ordinateur de bureau complet d'occasion",
    reference: "PC-OCC-01",
    price: 0,
    stock: 3,
    status: "in_stock",
    categoryId: "ordinateurs",
    images: ["/images/ordinateur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },

  // ── Accessoires Starlink ──
  {
    id: "stl-01",
    slug: "chargeur-starlink-v4",
    name: "Chargeur Starlink V4",
    reference: "STL-CHG-V4",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/chargeur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "stl-02",
    slug: "chargeur-starlink-mini",
    name: "Chargeur Starlink Mini",
    reference: "STL-CHG-MN",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/chargeur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "stl-03",
    slug: "cable-starlink-v4",
    name: "Câble Starlink V4",
    reference: "STL-CBL-V4",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/cable.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "stl-04",
    slug: "cable-starlink-mini",
    name: "Câble Starlink Mini",
    reference: "STL-CBL-MN",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/cable.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "stl-05",
    slug: "cable-usbc-starlink-mini",
    name: "Câble USB-C pour Starlink Mini",
    reference: "STL-USBC-MN",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/connecteur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "stl-06",
    slug: "support-starlink-v4",
    name: "Support Starlink V4",
    reference: "STL-SUP-V4",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/fixations.jpg"],
    installationAvailable: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "stl-07",
    slug: "routeur-starlink-v4",
    name: "Routeur Starlink V4",
    reference: "STL-RTR-V4",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/routeur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "stl-08",
    slug: "routeur-starlink-v2",
    name: "Routeur Starlink V2",
    reference: "STL-RTR-V2",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-starlink",
    images: ["/images/routeur.jpg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },

  // ── Accessoires informatique ──
  {
    id: "inf-01",
    slug: "repeteur-wifi-tplink",
    name: "Répéteur WiFi TP-Link",
    reference: "RPT-TPL",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/repetiteur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "inf-02",
    slug: "repeteur-wifi-mobilcom",
    name: "Répéteur WiFi Mobilcom",
    reference: "RPT-MBC",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/repetiteur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "inf-03",
    slug: "ecran-ordinateur",
    name: "Écran / moniteur d'ordinateur",
    reference: "ECR-01",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/ecran.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "inf-04",
    slug: "batterie-ordinateur-portable",
    name: "Batterie pour ordinateur portable",
    reference: "BAT-LAP",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/batterie.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "inf-05",
    slug: "clavier-ordinateur",
    name: "Clavier d'ordinateur",
    reference: "CLV-01",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/clavier.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "inf-06",
    slug: "chargeur-laptop",
    name: "Chargeur pour laptop",
    reference: "CHG-LAP",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "accessoires-informatique",
    images: ["/images/chargeur.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },

  // ── Services ──
  {
    id: "srv-01",
    slug: "maintenance-informatique",
    name: "Maintenance & dépannage informatique",
    reference: "SRV-MAINT",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "services",
    images: ["/images/maintenance.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "srv-02",
    slug: "installation-systeme-logiciels",
    name: "Installation système & logiciels",
    reference: "SRV-SYS",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "services",
    images: ["/images/logiciels.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "srv-03",
    slug: "installation-cameras-surveillance",
    name: "Installation de caméras de surveillance",
    reference: "SRV-CAM",
    price: 0,
    stock: 0,
    status: "in_stock",
    categoryId: "services",
    images: ["/images/camera.svg"],
    installationAvailable: false,
    createdAt: new Date().toISOString(),
  },
];

export const FLASH_SALE_END = Date.now() + 2 * 24 * 3600 * 1000; // +2 jours

// Sélection mise en avant dans la vente flash (les prix promos seront
// définis par l'admin à la publication — "Prix sur demande" sinon)
export const FLASH_PRODUCTS = DEMO_PRODUCTS.filter((p) =>
  ["ord-01", "stl-01", "stl-03", "inf-01"].includes(p.id)
);
